name: CD Pipeline

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker pull $DOCKER_USER/bikeshare-api:latest
        
      - name: Free Port 8001 if in use
        run: |
          if lsof -i:8001; then
            echo "Port 8001 is in use. Killing the process using it..."
            sudo fuser -k 8001/tcp
          else
            echo "Port 8001 is free."
          fi
      
      - name: Delete Old Docker Container
        run: sudo docker rm -f bikeshare-api-container || true
    
      - name: Run Docker Container
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: |
          PORT=8001
          while lsof -i:$PORT; do
            echo "Port $PORT is in use. Trying the next port..."
            PORT=$((PORT+1))
          done
          echo "Using port $PORT."
          sudo docker run -it -d -p 8003:8003 --name bikeshare-api-container $DOCKER_USER/bikeshare-api:latest
